---
environment:
  ssh_private_key_file: &ssh_private_key_file "{{ lookup('env', 'SSH_PRIVATE_KEY_FILE') | default('~/.ssh/k8s/k8s_id_rsa', True) }}"
all:
  hosts:
    localhost: # localhost connection parameters, used for storing configuration while transferring it between nodes
      ansible_connection: local
    nexus:
      ansible_host: 3.8.89.26
      ansible_ssh_user: ubuntu
      ansible_connection: ssh
      ansible_ssh_private_key_file: *ssh_private_key_file
      ansible_ssh_port: 22
  vars:
    AWS_DEFAULT_REGION: "eu-west-2"
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID' ) }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY' ) }}"
    ansible_python_interpreter: /usr/bin/python3